### ISSUE TITLE
SO-O或P-SO的pth模型文件可以提供吗？

### ISSUE THREAD

**Issue by xuzhuang1996** [charent/pytorch_IE_model#7]
您好。最近在研究知识图谱，打算提取三元组，看到您的工作效果很棒，想问下：
1. SO-O或P-SO的pth模型文件可以提供吗？
2. 如果自己训练，默认不选择预训练模型。那如果选择bert或者其他模型，效果有对比吗？

**Comment by charent** [comment]
1. 暂时不提供模型权重（几年前的项目了，不知道权重仍哪里了），训练数据和模型参数都是公开的，你可以自己训练一个，耗时大概1天左右。
2. 使用预训练bert进行后续训练，我没有做过（因为当时我手头只有一张1050ti的卡😭），理论上应该会有几个点的提升，因为训练数据、测试数据里面很多都是没标全的，有漏标的。
